package com.silentpulse.messenger.common.util

internal data class CityRegionHint(val country: String, val region: String, val place: String)

// Generated from the 2026-09-30 Open-Meteo / GeoNames audit of the explicit city aliases.
// Describes each existing alias; it never changes that alias's selected IANA zone.
internal val cityRegionHints: Map<String, CityRegionHint> = mapOf(
    "new york" to CityRegionHint("US", "New York", "New York"),
    "nyc" to CityRegionHint("US", "New York", "New York"),
    "los angeles" to CityRegionHint("US", "California", "Los Angeles"),
    "la" to CityRegionHint("US", "California", "Los Angeles"),
    "san francisco" to CityRegionHint("US", "California", "San Francisco"),
    "sf" to CityRegionHint("US", "California", "San Francisco"),
    "san diego" to CityRegionHint("US", "California", "San Diego"),
    "chicago" to CityRegionHint("US", "Illinois", "Chicago"),
    "dallas" to CityRegionHint("US", "Texas", "Dallas"),
    "houston" to CityRegionHint("US", "Texas", "Houston"),
    "san antonio" to CityRegionHint("US", "Texas", "San Antonio"),
    "austin" to CityRegionHint("US", "Texas", "Austin"),
    "denver" to CityRegionHint("US", "Colorado", "Denver"),
    "phoenix" to CityRegionHint("US", "Arizona", "Phoenix"),
    "seattle" to CityRegionHint("US", "Washington", "Seattle"),
    "portland" to CityRegionHint("US", "Oregon", "Portland"),
    "miami" to CityRegionHint("US", "Florida", "Miami"),
    "atlanta" to CityRegionHint("US", "Georgia", "Atlanta"),
    "boston" to CityRegionHint("US", "Massachusetts", "Boston"),
    "philadelphia" to CityRegionHint("US", "Pennsylvania", "Philadelphia"),
    "detroit" to CityRegionHint("US", "Michigan", "Detroit"),
    "minneapolis" to CityRegionHint("US", "Minnesota", "Minneapolis"),
    "st louis" to CityRegionHint("US", "Oklahoma", "Saint Louis"),
    "saint louis" to CityRegionHint("US", "Oklahoma", "Saint Louis"),
    "kansas city" to CityRegionHint("US", "Missouri", "Kansas City"),
    "salt lake city" to CityRegionHint("US", "Utah", "Salt Lake City"),
    "las vegas" to CityRegionHint("US", "Nevada", "Las Vegas"),
    "honolulu" to CityRegionHint("US", "Hawaii", "Honolulu"),
    "hawaii" to CityRegionHint("US", "Hawaii", "Honolulu"),
    "anchorage" to CityRegionHint("US", "Alaska", "Anchorage"),
    "alaska" to CityRegionHint("US", "Alaska", "Anchorage"),
    "nashville" to CityRegionHint("US", "Tennessee", "Nashville"),
    "memphis" to CityRegionHint("US", "Tennessee", "Memphis"),
    "louisville" to CityRegionHint("US", "Kentucky", "Louisville"),
    "indianapolis" to CityRegionHint("US", "Indiana", "Indianapolis"),
    "columbus" to CityRegionHint("US", "Ohio", "Columbus"),
    "charlotte" to CityRegionHint("US", "North Carolina", "Charlotte"),
    "pittsburgh" to CityRegionHint("US", "Pennsylvania", "Pittsburgh"),
    "baltimore" to CityRegionHint("US", "Maryland", "Baltimore"),
    "washington" to CityRegionHint("US", "Pennsylvania", "Washington"),
    "dc" to CityRegionHint("US", "Pennsylvania", "Washington"),
    "washington dc" to CityRegionHint("US", "Pennsylvania", "Washington"),
    "orlando" to CityRegionHint("US", "Florida", "Orlando"),
    "tampa" to CityRegionHint("US", "Florida", "Tampa"),
    "jacksonville" to CityRegionHint("US", "Florida", "Jacksonville"),
    "milwaukee" to CityRegionHint("US", "Wisconsin", "Milwaukee"),
    "oklahoma city" to CityRegionHint("US", "Oklahoma", "Oklahoma City"),
    "albuquerque" to CityRegionHint("US", "New Mexico", "Albuquerque"),
    "tucson" to CityRegionHint("US", "Arizona", "Tucson"),
    "raleigh" to CityRegionHint("US", "North Carolina", "Raleigh"),
    "richmond" to CityRegionHint("US", "Virginia", "Richmond"),
    "new orleans" to CityRegionHint("US", "Louisiana", "New Orleans"),
    "lafayette" to CityRegionHint("US", "Louisiana", "Lafayette"),
    "baton rouge" to CityRegionHint("US", "Louisiana", "Baton Rouge"),
    "birmingham" to CityRegionHint("US", "Alabama", "Birmingham"),
    "omaha" to CityRegionHint("US", "Nebraska", "Omaha"),
    "des moines" to CityRegionHint("US", "Iowa", "Des Moines"),
    "little rock" to CityRegionHint("US", "Arkansas", "Little Rock"),
    "jackson" to CityRegionHint("US", "Mississippi", "Jackson"),
    "wichita" to CityRegionHint("US", "Kansas", "Wichita"),
    "tulsa" to CityRegionHint("US", "Oklahoma", "Tulsa"),
    "el paso" to CityRegionHint("US", "Texas", "El Paso"),
    "boise" to CityRegionHint("US", "Idaho", "Boise"),
    "reno" to CityRegionHint("US", "Nevada", "Reno"),
    "sacramento" to CityRegionHint("US", "California", "Sacramento"),
    "fresno" to CityRegionHint("US", "California", "Fresno"),
    "oakland" to CityRegionHint("US", "California", "Oakland"),
    "san jose" to CityRegionHint("US", "California", "San Jose"),
    "spokane" to CityRegionHint("US", "Washington", "Spokane"),
    "toronto" to CityRegionHint("CA", "Ontario", "Toronto"),
    "vancouver" to CityRegionHint("CA", "British Columbia", "Vancouver"),
    "montreal" to CityRegionHint("CA", "Quebec", "Montreal"),
    "ottawa" to CityRegionHint("CA", "Ontario", "Ottawa"),
    "calgary" to CityRegionHint("CA", "Alberta", "Calgary"),
    "edmonton" to CityRegionHint("CA", "Alberta", "Edmonton"),
    "winnipeg" to CityRegionHint("CA", "Manitoba", "Winnipeg"),
    "halifax" to CityRegionHint("CA", "Nova Scotia", "Halifax"),
    "st johns" to CityRegionHint("CA", "Newfoundland and Labrador", "St. John's"),
    "saint johns" to CityRegionHint("CA", "Newfoundland and Labrador", "St. John's"),
    "mexico city" to CityRegionHint("MX", "Mexico City", "Mexico City"),
    "guadalajara" to CityRegionHint("MX", "Jalisco", "Guadalajara"),
    "monterrey" to CityRegionHint("MX", "Nuevo Le\u00f3n", "Monterrey"),
    "cancun" to CityRegionHint("MX", "Quintana Roo", "Canc\u00fan"),
    "tijuana" to CityRegionHint("MX", "Baja California", "Tijuana"),
    "sao paulo" to CityRegionHint("BR", "S\u00e3o Paulo", "S\u00e3o Paulo"),
    "rio de janeiro" to CityRegionHint("BR", "Rio de Janeiro", "Rio de Janeiro"),
    "rio" to CityRegionHint("BR", "Rio de Janeiro", "Rio de Janeiro"),
    "buenos aires" to CityRegionHint("AR", "Buenos Aires F.D.", "Buenos Aires"),
    "bogota" to CityRegionHint("CO", "Bogota D.C.", "Bogot\u00e1"),
    "lima" to CityRegionHint("PE", "Lima Province", "Lima"),
    "santiago" to CityRegionHint("CL", "Santiago Metropolitan", "Santiago"),
    "caracas" to CityRegionHint("VE", "Distrito Federal", "Caracas"),
    "quito" to CityRegionHint("EC", "Pichincha", "Quito"),
    "montevideo" to CityRegionHint("UY", "Montevideo Department", "Montevideo"),
    "asuncion" to CityRegionHint("PY", "Asuncion", "Asunci\u00f3n"),
    "la paz" to CityRegionHint("BO", "La Paz Department", "La Paz"),
    "medellin" to CityRegionHint("CO", "Antioquia", "Medell\u00edn"),
    "london" to CityRegionHint("GB", "England", "London"),
    "paris" to CityRegionHint("FR", "\u00cele-de-France Region", "Paris"),
    "berlin" to CityRegionHint("DE", "State of Berlin", "Berlin"),
    "munich" to CityRegionHint("DE", "Bavaria", "Munich"),
    "frankfurt" to CityRegionHint("DE", "Bavaria", "Frankfurt"),
    "hamburg" to CityRegionHint("DE", "Free and Hanseatic City of Hamburg", "Hamburg"),
    "rome" to CityRegionHint("IT", "Lazio", "Rome"),
    "milan" to CityRegionHint("IT", "Lombardy", "Milan"),
    "madrid" to CityRegionHint("ES", "Madrid", "Madrid"),
    "barcelona" to CityRegionHint("ES", "Catalonia", "Barcelona"),
    "amsterdam" to CityRegionHint("NL", "North Holland", "Amsterdam"),
    "brussels" to CityRegionHint("BE", "Brussels Capital", "Brussels"),
    "vienna" to CityRegionHint("AT", "State of Vienna", "Vienna"),
    "zurich" to CityRegionHint("CH", "Canton of Zurich", "Zurich"),
    "geneva" to CityRegionHint("CH", "Canton of Geneva", "Geneva"),
    "stockholm" to CityRegionHint("SE", "Stockholm County", "Stockholm"),
    "oslo" to CityRegionHint("NO", "Oslo", "Oslo"),
    "copenhagen" to CityRegionHint("DK", "Capital Region", "Copenhagen"),
    "helsinki" to CityRegionHint("FI", "Uusimaa", "Helsinki"),
    "warsaw" to CityRegionHint("PL", "Mazovia", "Warsaw"),
    "krakow" to CityRegionHint("PL", "Lesser Poland", "Krakow"),
    "prague" to CityRegionHint("CZ", "Prague", "Prague"),
    "budapest" to CityRegionHint("HU", "Budapest", "Budapest"),
    "bucharest" to CityRegionHint("RO", "Bucharest", "Bucharest"),
    "athens" to CityRegionHint("GR", "Attica", "Athens"),
    "istanbul" to CityRegionHint("TR", "Istanbul", "Istanbul"),
    "moscow" to CityRegionHint("RU", "Moscow", "Moscow"),
    "saint petersburg" to CityRegionHint("RU", "St.-Petersburg", "St Petersburg"),
    "st petersburg" to CityRegionHint("RU", "St.-Petersburg", "St Petersburg"),
    "kiev" to CityRegionHint("UA", "Kyiv City", "Kyiv"),
    "kyiv" to CityRegionHint("UA", "Kyiv City", "Kyiv"),
    "dublin" to CityRegionHint("IE", "Leinster", "Dublin"),
    "edinburgh" to CityRegionHint("GB", "Scotland", "Edinburgh"),
    "lisbon" to CityRegionHint("PT", "Lisbon District", "Lisbon"),
    "belgrade" to CityRegionHint("RS", "Central Serbia", "Belgrade"),
    "zagreb" to CityRegionHint("HR", "City of Zagreb", "Zagreb"),
    "sofia" to CityRegionHint("BG", "Sofia-Capital", "Sofia"),
    "riga" to CityRegionHint("LV", "Riga", "Riga"),
    "tallinn" to CityRegionHint("EE", "Harju", "Tallinn"),
    "vilnius" to CityRegionHint("LT", "Vilnius", "Vilnius"),
    "minsk" to CityRegionHint("BY", "Minsk City", "Minsk"),
    "dubai" to CityRegionHint("AE", "Dubai", "Dubai"),
    "abu dhabi" to CityRegionHint("AE", "Abu Dhabi Emirate", "Abu Dhabi"),
    "tel aviv" to CityRegionHint("IL", "Tel Aviv", "Tel Aviv"),
    "jerusalem" to CityRegionHint("IL", "Jerusalem", "Jerusalem"),
    "israel" to CityRegionHint("IL", "Jerusalem", "Jerusalem"),
    "riyadh" to CityRegionHint("SA", "Riyadh Region", "Riyadh"),
    "jeddah" to CityRegionHint("SA", "Mecca Region", "Jeddah"),
    "doha" to CityRegionHint("QA", "Baladiyat ad Dawhah", "Doha"),
    "tehran" to CityRegionHint("IR", "Tehran", "Tehran"),
    "baghdad" to CityRegionHint("IQ", "Baghdad", "Baghdad"),
    "beirut" to CityRegionHint("LB", "Beirut", "Beirut"),
    "amman" to CityRegionHint("JO", "Amman Governorate", "Amman"),
    "kuwait city" to CityRegionHint("KW", "Al Asimah", "Kuwait City"),
    "muscat" to CityRegionHint("OM", "Muscat", "Muscat"),
    "mumbai" to CityRegionHint("IN", "Maharashtra", "Mumbai"),
    "delhi" to CityRegionHint("IN", "National Capital Territory of Delhi", "Delhi"),
    "new delhi" to CityRegionHint("IN", "National Capital Territory of Delhi", "New Delhi"),
    "india" to CityRegionHint("IN", "West Bengal", "Kolkata"),
    "bangalore" to CityRegionHint("IN", "Karnataka", "Bengaluru"),
    "kolkata" to CityRegionHint("IN", "West Bengal", "Kolkata"),
    "chennai" to CityRegionHint("IN", "Tamil Nadu", "Chennai"),
    "hyderabad" to CityRegionHint("IN", "Telangana", "Hyderabad"),
    "karachi" to CityRegionHint("PK", "Sindh", "Karachi"),
    "islamabad" to CityRegionHint("PK", "Islamabad", "Islamabad"),
    "lahore" to CityRegionHint("PK", "Punjab", "Lahore"),
    "dhaka" to CityRegionHint("BD", "Dhaka Division", "Dhaka"),
    "bangkok" to CityRegionHint("TH", "Bangkok", "Bangkok"),
    "singapore" to CityRegionHint("SG", "", "Singapore"),
    "kuala lumpur" to CityRegionHint("MY", "Kuala Lumpur", "Kuala Lumpur"),
    "jakarta" to CityRegionHint("ID", "Jakarta Special Capital Region", "Jakarta"),
    "ho chi minh" to CityRegionHint("VN", "Ho Chi Minh City (HCMC)", "Ho Chi Minh City"),
    "saigon" to CityRegionHint("VN", "Ho Chi Minh City (HCMC)", "Ho Chi Minh City"),
    "hanoi" to CityRegionHint("VN", "Hanoi", "Hanoi"),
    "manila" to CityRegionHint("PH", "National Capital Region", "Manila"),
    "colombo" to CityRegionHint("LK", "Western Province", "Colombo"),
    "yangon" to CityRegionHint("MM", "Yangon", "Yangon"),
    "phnom penh" to CityRegionHint("KH", "Phnom Penh", "Phnom Penh"),
    "kathmandu" to CityRegionHint("NP", "Bagmati Province", "Kathmandu"),
    "hong kong" to CityRegionHint("HK", "", "Hong Kong"),
    "taipei" to CityRegionHint("TW", "Taiwan", "Taipei"),
    "tokyo" to CityRegionHint("JP", "Tokyo", "Tokyo"),
    "japan" to CityRegionHint("JP", "Tokyo", "Tokyo"),
    "osaka" to CityRegionHint("JP", "Osaka", "Osaka"),
    "seoul" to CityRegionHint("KR", "Seoul", "Seoul"),
    "korea" to CityRegionHint("KR", "Seoul", "Seoul"),
    "beijing" to CityRegionHint("CN", "Beijing Municipality", "Beijing"),
    "shanghai" to CityRegionHint("CN", "Shanghai Municipality", "Shanghai"),
    "china" to CityRegionHint("CN", "Shanghai Municipality", "Shanghai"),
    "shenzhen" to CityRegionHint("CN", "Guangdong", "Shenzhen"),
    "guangzhou" to CityRegionHint("CN", "Guangdong", "Guangzhou"),
    "ulaanbaatar" to CityRegionHint("MN", "Ulaanbaatar", "Ulaanbaatar"),
    "sydney" to CityRegionHint("AU", "New South Wales", "Sydney"),
    "melbourne" to CityRegionHint("AU", "Victoria", "Melbourne"),
    "brisbane" to CityRegionHint("AU", "Queensland", "Brisbane"),
    "perth" to CityRegionHint("AU", "Western Australia", "Perth"),
    "adelaide" to CityRegionHint("AU", "South Australia", "Adelaide"),
    "auckland" to CityRegionHint("NZ", "Auckland", "Auckland"),
    "new zealand" to CityRegionHint("NZ", "Auckland", "Auckland"),
    "wellington" to CityRegionHint("NZ", "Wellington Region", "Wellington"),
    "fiji" to CityRegionHint("FJ", "Central", "Suva"),
    "cairo" to CityRegionHint("EG", "Cairo Governorate", "Cairo"),
    "johannesburg" to CityRegionHint("ZA", "Gauteng", "Johannesburg"),
    "cape town" to CityRegionHint("ZA", "Western Cape", "Cape Town"),
    "lagos" to CityRegionHint("NG", "Lagos", "Lagos"),
    "nairobi" to CityRegionHint("KE", "Nairobi County", "Nairobi"),
    "casablanca" to CityRegionHint("MA", "Casablanca-Settat", "Casablanca"),
    "addis ababa" to CityRegionHint("ET", "Addis Ababa", "Addis Ababa"),
    "dar es salaam" to CityRegionHint("TZ", "Dar es Salaam Region", "Dar es Salaam"),
    "accra" to CityRegionHint("GH", "Greater Accra Region", "Accra"),
    "dakar" to CityRegionHint("SN", "Dakar", "Dakar"),
    "kabul" to CityRegionHint("AF", "Kabul", "Kabul"),
    "tashkent" to CityRegionHint("UZ", "Tashkent", "Tashkent"),
    "almaty" to CityRegionHint("KZ", "Almaty", "Almaty"),
    "baku" to CityRegionHint("AZ", "Baku City", "Baku"),
    "yerevan" to CityRegionHint("AM", "Yerevan", "Yerevan"),
    "tbilisi" to CityRegionHint("GE", "Tbilisi", "Tbilisi"),
)
